# 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asm_test_020201
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
